services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

  tests:
    image: "golang:1.19"
    container_name: test
    working_dir: /app
    command: [ "go", "test", "./..." ]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
