services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    entrypoint: ["/root/stress-test"]
    command: []

  tests:
    image: "golang:1.19"
    container_name: test
    working_dir: /app
    command: [ "go", "test", "./..." ]
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
